In [2]:
!pip install fg-data-profiling pandas numpy --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 29.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 22.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 79.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 44.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.3 MB/s eta 0:00:00

In [3]:
from IPython.core.application import ProfileAwareConfigLoader
import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport
from google.colab import files

In [4]:
uploaded= files.upload()

Saving Sales data.csv to Sales data.csv

In [5]:
df= pd.read_csv('Sales data.csv')

In [6]:
profile= ProfileReport(df, title="Pofiling Report", explorative= True)
profile.to_file('report.html')
files.download('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/21 [00:00<?, ?it/s]
  5%|▍         | 1/21 [00:00<00:09,  2.13it/s]
 10%|▉         | 2/21 [00:00<00:05,  3.60it/s]
 14%|█▍        | 3/21 [00:00<00:04,  3.82it/s]
 24%|██▍       | 5/21 [00:01<00:02,  5.50it/s]
 29%|██▊       | 6/21 [00:01<00:02,  6.04it/s]
 33%|███▎      | 7/21 [00:01<00:02,  5.32it/s]
 43%|████▎     | 9/21 [00:01<00:02,  5.68it/s]
 48%|████▊     | 10/21 [00:01<00:01,  5.79it/s]
 52%|█████▏    | 11/21 [00:02<00:02,  3.39it/s]
 57%|█████▋    | 12/21 [00:02<00:02,  3.96it/s]
 62%|██████▏   | 13/21 [00:03<00:02,  3.80it/s]
 67%|██████▋   | 14/21 [00:03<00:01,  4.37it/s]
 76%|███████▌  | 16/21 [00:03<00:00,  6.59it/s]
 86%|████████▌ | 18/21 [00:03<00:00,  8.48it/s]
100%|██████████| 21/21 [00:03<00:00,  5.66it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [7]:
df.shape

(51290, 21)

In [8]:
df.dtypes

order_id           object
order_date         object
ship_date          object
ship_mode          object
customer_name      object
segment            object
state              object
country            object
market             object
region             object
product_id         object
category           object
sub_category       object
product_name       object
sales              object
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority     object
year                int64
dtype: object

In [9]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [10]:
df.head(25)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.00,106.1400,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.10,36.0360,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.00,29.6400,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.50,-26.0550,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.10,37.7700,4.70,Medium,2011
5,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",55,2,0.10,15.3420,1.80,Medium,2011
6,CA-2011-1510,2/1/2011,6/1/2011,Standard Class,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,...,Technology,Machines,"Okidata Inkjet, Wireless",314,1,0.00,3.1200,24.10,Medium,2011
7,IN-2011-79397,3/1/2011,3/1/2011,Same Day,Kean Nguyen,Corporate,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Appliances,"Hoover Microwave, White",276,1,0.10,110.4120,125.32,Critical,2011
8,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Technology,Copiers,"Hewlett Wireless Fax, Laser",912,4,0.40,-319.4640,107.10,Low,2011
9,IZ-2011-4680,3/1/2011,7/1/2011,Standard Class,Lindsay Williams,Corporate,Ninawa,Iraq,EMEA,EMEA,...,Furniture,Chairs,"Novimex Swivel Stool, Set of Two",667,4,0.00,253.3200,81.26,High,2011
10,IN-2011-65159,3/1/2011,7/1/2011,Second Class,Larry Blacks,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,Office Supplies,Storage,"Tenex Lockers, Industrial",338,3,0.45,-122.8005,33.75,High,2011
11,IN-2011-65159,3/1/2011,7/1/2011,Second Class,Larry Blacks,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,Furniture,Tables,"Chromcraft Round Table, Adjustable Height",211,1,0.55,-70.3995,21.32,High,2011
12,ES-2011-4869686,3/1/2011,7/1/2011,Standard Class,Dorothy Dickinson,Consumer,England,United Kingdom,EU,North,...,Furniture,Bookcases,"Dania Corner Shelving, Traditional",854,7,0.00,290.4300,12.56,Medium,2011
13,IN-2011-33652,3/1/2011,9/1/2011,Standard Class,Dennis Pardue,Home Office,Sarawak,Malaysia,APAC,Southeast Asia,...,Technology,Copiers,"Hewlett Fax and Copier, Laser",193,1,0.00,50.1300,10.40,Medium,2011
14,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Furniture,Chairs,"Hon Rocking Chair, Set of Two",159,2,0.40,-95.6760,10.07,Low,2011
15,MX-2011-160234,3/1/2011,7/1/2011,Standard Class,Stewart Visinsky,Consumer,Guatemala,Guatemala,LATAM,Central,...,Technology,Phones,"Nokia Headset, VoIP",195,4,0.00,44.8800,8.43,Medium,2011
16,IR-2011-770,3/1/2011,7/1/2011,Standard Class,Jas O'Carroll,Consumer,Yazd,Iran,EMEA,EMEA,...,Office Supplies,Appliances,"Breville Coffee Grinder, Black",123,2,0.00,42.9000,8.41,Medium,2011
17,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Technology,Accessories,"Belkin Numeric Keypad, Bluetooth",69,2,0.40,3.4200,8.34,Low,2011
18,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Furniture,Chairs,"SAFCO Chairmat, Black",69,2,0.40,-26.4120,8.17,Low,2011
19,ID-2011-12596,3/1/2011,8/1/2011,Standard Class,Chris McAfee,Consumer,Nakhon Ratchasima,Thailand,APAC,Southeast Asia,...,Office Supplies,Storage,"Smead File Cart, Blue",135,2,0.47,-45.9018,7.74,Medium,2011
20,IN-2011-79397,3/1/2011,3/1/2011,Same Day,Kean Nguyen,Corporate,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Labels,"Avery Color Coded Labels, Laser Printer Compat...",36,3,0.10,4.7430,7.46,Critical,2011
21,IR-2011-7690,3/1/2011,8/1/2011,Second Class,Nat Gilpin,Corporate,Razavi Khorasan,Iran,EMEA,EMEA,...,Office Supplies,Art,"BIC Sketch Pad, Water Color",52,1,0.00,7.7700,5.91,High,2011
22,IR-2011-770,3/1/2011,7/1/2011,Standard Class,Jas O'Carroll,Consumer,Yazd,Iran,EMEA,EMEA,...,Office Supplies,Storage,"Rogers Folders, Industrial",62,2,0.00,8.7000,5.16,Medium,2011
23,TZ-2011-7370,3/1/2011,8/1/2011,Standard Class,Jack Garza,Consumer,Dar Es Salaam,Tanzania,Africa,Africa,...,Office Supplies,Supplies,"Stiletto Scissors, Serrated",81,4,0.00,26.7600,5.11,Medium,2011
24,IZ-2011-4680,3/1/2011,7/1/2011,Standard Class,Lindsay Williams,Corporate,Ninawa,Iraq,EMEA,EMEA,...,Office Supplies,Envelopes,"Cameo Interoffice Envelope, Set of 50",47,1,0.00,17.0700,3.57,High,2011

In [11]:
#Standardise columns name
df.columns=(
    df.columns
    .str.replace(' ','_')
    .str.lower()
    .str.strip()
)

In [12]:
df.describe(include="all")

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
count,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,...,51290,51290,51290,51290,51290.000000,51290.000000,51290.000000,51290.000000,51290,51290.000000
unique,25035,1430,1464,4,795,3,1094,147,7,13,...,3,17,3788,2246,NaN,NaN,NaN,NaN,4,NaN
top,CA-2014-100111,18/06/2014,22/11/2014,Standard Class,Muhammed Yedwab,Consumer,California,United States,APAC,Central,...,Office Supplies,Binders,Staples,13,NaN,NaN,NaN,NaN,Medium,NaN
freq,14,135,130,30775,108,26518,2001,9994,11002,11117,...,31273,6152,227,589,NaN,NaN,NaN,NaN,29433,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.476545,0.142908,28.641740,26.375915,NaN,2012.777208
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.278766,0.212280,174.424113,57.296804,NaN,1.098931
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.000000,0.000000,-6599.978000,0.000000,NaN,2011.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.000000,0.000000,0.000000,2.610000,NaN,2012.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.000000,0.000000,9.240000,7.790000,NaN,2013.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.000000,0.200000,36.810000,24.450000,NaN,2014.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,14.000000,0.850000,8399.976000,933.570000,NaN,2014.000000

In [13]:
missing=df.isnull().mean()*100
print(missing)

order_id          0.0
order_date        0.0
ship_date         0.0
ship_mode         0.0
customer_name     0.0
segment           0.0
state             0.0
country           0.0
market            0.0
region            0.0
product_id        0.0
category          0.0
sub_category      0.0
product_name      0.0
sales             0.0
quantity          0.0
discount          0.0
profit            0.0
shipping_cost     0.0
order_priority    0.0
year              0.0
dtype: float64

In [14]:
n_dupes=df.duplicated().sum()
n_dupes

np.int64(0)

In [15]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [16]:
df["sales"].dtype

dtype('O')

In [17]:
#Convertir sales
df["sales"] = pd.to_numeric(
    df["sales"].astype(str).str.replace(",", "", regex=False),
    errors="coerce"
)

In [18]:
print(df["sales"].dtype)
print(df["sales"].isnull().sum())

int64
0

In [19]:
#Convertir les dates
df["order_date"] = pd.to_datetime(
    df["order_date"],
    dayfirst=True,
    errors="coerce"
)

In [21]:
df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    dayfirst=True,
    errors="coerce")

In [22]:
print(df["order_date"].dtype)
print(df["ship_date"].dtype)

datetime64[ns]
datetime64[ns]

In [23]:
print("Dates commande invalides :", df["order_date"].isnull().sum())
print("Dates expédition invalides :", df["ship_date"].isnull().sum())

Dates commande invalides : 0
Dates expédition invalides : 0

In [26]:
df["year"].dtype

dtype('int64')

In [27]:
#la cohérence entre year et order_date
year_from_date = df["order_date"].dt.year

print(
    "Nombre d'incohérences :",
    (year_from_date != df["year"]).sum()
)

Nombre d'incohérences : 0

In [28]:
print(df["quantity"].describe())

count    51290.000000
mean         3.476545
std          2.278766
min          1.000000
25%          2.000000
50%          3.000000
75%          5.000000
max         14.000000
Name: quantity, dtype: float64

In [29]:
print("Quantités <= 0 :", (df["quantity"] <= 0).sum())

Quantités <= 0 : 0

In [31]:
#Vérifier les remises
df["discount"]

0        0.0
1        0.1
2        0.0
3        0.5
4        0.1
        ...
51285    0.2
51286    0.0
51287    0.0
51288    0.0
51289    0.2
Name: discount, Length: 51290, dtype: float64

In [32]:
print(df["discount"].describe())

count    51290.000000
mean         0.142908
std          0.212280
min          0.000000
25%          0.000000
50%          0.000000
75%          0.200000
max          0.850000
Name: discount, dtype: float64

In [33]:
print(
    "Discount < 0 :",
    (df["discount"] < 0).sum()
)

print(
    "Discount > 1 :",
    (df["discount"] > 1).sum()
)

Discount < 0 : 0
Discount > 1 : 0

In [34]:
#Vérifier le profit
print(df["profit"].describe())

count    51290.000000
mean        28.641740
std        174.424113
min      -6599.978000
25%          0.000000
50%          9.240000
75%         36.810000
max       8399.976000
Name: profit, dtype: float64

In [35]:
print("Profit négatif :", (df["profit"] < 0).sum())

Profit négatif : 12543

In [36]:
#les frais de livraison
print(df["shipping_cost"].describe())

count    51290.000000
mean        26.375915
std         57.296804
min          0.000000
25%          2.610000
50%          7.790000
75%         24.450000
max        933.570000
Name: shipping_cost, dtype: float64

In [37]:
print(
    "Shipping cost négatif :",
    (df["shipping_cost"] < 0).sum()
)

Shipping cost négatif : 0

In [38]:
#Vérifier la logique des dates
df["shipping_days"] = (
    df["ship_date"] - df["order_date"]
).dt.days

In [39]:
df["shipping_days"].describe()

count    51290.000000
mean         3.969370
std          1.729437
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: shipping_days, dtype: float64

In [40]:
print(
    "Dates incohérentes :",
    (df["shipping_days"] < 0).sum()
)

Dates incohérentes : 0

Créer les variables utiles pour l'analyse

Maintenant que les données sont propres, nous pouvons créer des variables analytiques.

In [41]:
df["month"] = df["order_date"].dt.month

In [42]:
df["month_name"] = df["order_date"].dt.month_name()

In [43]:
df["quarter"] = df["order_date"].dt.quarter

In [44]:
df["day"] = df["order_date"].dt.day

In [45]:
df["day_of_week"] = df["order_date"].dt.day_name()

In [46]:
#creer de la marge
df["profit_margin"] = np.where(
    df["sales"] != 0,
    (df["profit"] / df["sales"]) * 100,
    0
)

In [47]:
print(
    "Sales = 0 :",
    (df["sales"] == 0).sum()
)

Sales = 0 : 1

In [48]:
df[df["sales"] == 0]

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,shipping_cost,order_priority,year,shipping_days,month,month_name,quarter,day,day_of_week,profit_margin
40017,US-2014-102288,2014-06-20,2014-06-24,Standard Class,Zuschuss Carroll,Consumer,Texas,United States,US,Central,...,0.01,Medium,2014,4,6,June,2,20,Friday,0.0

In [49]:
#Vérification finale
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  datetime64[ns]
 2   ship_date       51290 non-null  datetime64[ns]
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  int64
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
 21  shipping_days   51290 non-null  int64
 22  month           51290 non-null  int32
 23  month_name      51290 non-null  object
 24  quarter         51290 non-null  int32
 25  day             51290 non-null  int32
 26  day_of_week     51290 non-null  object
 27  profit_margin   51290 non-null  float64
dtypes: datetime64[ns](2), float64(4), int32(3), int64(4), object(15)
memory usage: 10.4+ MB
None

In [50]:
print(df.isnull().sum())

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
shipping_days     0
month             0
month_name        0
quarter           0
day               0
day_of_week       0
profit_margin     0
dtype: int64

In [51]:
print("Doublons :", df.duplicated().sum())

Doublons : 0

In [52]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,shipping_cost,order_priority,year,shipping_days,month,month_name,quarter,day,day_of_week,profit_margin
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,35.46,Medium,2011,5,1,January,1,1,Saturday,26.014706
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,9.72,Medium,2011,7,1,January,1,1,Saturday,30.030000
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,8.17,High,2011,4,1,January,1,1,Saturday,44.909091
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,4.82,High,2011,4,1,January,1,1,Saturday,-57.900000
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,4.70,Medium,2011,7,1,January,1,1,Saturday,33.131579

In [53]:
df.to_csv(
    "Sales_data_cleaned.csv",
    index=False
)