In [1]:
!pip install fg-data-profiling pandas numpy --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.3/400.3 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 35.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 3.9 MB/s eta 0:00:00

In [2]:
from IPython.core.application import ProfileAwareConfigLoader
import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport
from google.colab import files

In [3]:
uploaded= files.upload()

Saving Sales data.csv to Sales data.csv

In [4]:
df= pd.read_csv('Sales data.csv')

In [5]:
profile= ProfileReport(df, title="Pofiling Report", explorative= True)
profile.to_file('report.html')
files.download('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/21 [00:00<?, ?it/s]
  5%|▍         | 1/21 [00:00<00:09,  2.09it/s]
 14%|█▍        | 3/21 [00:00<00:05,  3.48it/s]
 29%|██▊       | 6/21 [00:01<00:02,  5.80it/s]
 33%|███▎      | 7/21 [00:01<00:02,  5.59it/s]
 38%|███▊      | 8/21 [00:01<00:02,  6.14it/s]
 43%|████▎     | 9/21 [00:01<00:02,  5.83it/s]
 48%|████▊     | 10/21 [00:01<00:01,  5.90it/s]
 52%|█████▏    | 11/21 [00:02<00:02,  3.93it/s]
 62%|██████▏   | 13/21 [00:02<00:02,  3.72it/s]
 67%|██████▋   | 14/21 [00:03<00:01,  4.15it/s]
 71%|███████▏  | 15/21 [00:03<00:01,  3.93it/s]
 86%|████████▌ | 18/21 [00:03<00:00,  7.14it/s]
100%|██████████| 21/21 [00:03<00:00,  5.30it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
df.shape

(51290, 21)

In [9]:
df.dtypes

order_id           object
order_date         object
ship_date          object
ship_mode          object
customer_name      object
segment            object
state              object
country            object
market             object
region             object
product_id         object
category           object
sub_category       object
product_name       object
sales              object
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority     object
year                int64
dtype: object

In [10]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [17]:
df.head(25)

           order_id order_date ship_date  ... shipping_cost order_priority  year
0      AG-2011-2040   1/1/2011  6/1/2011  ...         35.46         Medium  2011
1     IN-2011-47883   1/1/2011  8/1/2011  ...          9.72         Medium  2011
2      HU-2011-1220   1/1/2011  5/1/2011  ...          8.17           High  2011
3   IT-2011-3647632   1/1/2011  5/1/2011  ...          4.82           High  2011
4     IN-2011-47883   1/1/2011  8/1/2011  ...          4.70         Medium  2011
5     IN-2011-47883   1/1/2011  8/1/2011  ...          1.80         Medium  2011
6      CA-2011-1510   2/1/2011  6/1/2011  ...         24.10         Medium  2011
7     IN-2011-79397   3/1/2011  3/1/2011  ...        125.32       Critical  2011
8     ID-2011-80230   3/1/2011  9/1/2011  ...        107.10            Low  2011
9      IZ-2011-4680   3/1/2011  7/1/2011  ...         81.26           High  2011
10    IN-2011-65159   3/1/2011  7/1/2011  ...         33.75           High  2011
11    IN-2011-65159   3/1/2011  7/1/2011  ...         21.32           High  2011
12  ES-2011-4869686   3/1/2011  7/1/2011  ...         12.56         Medium  2011
13    IN-2011-33652   3/1/2011  9/1/2011  ...         10.40         Medium  2011
14    ID-2011-80230   3/1/2011  9/1/2011  ...         10.07            Low  2011
15   MX-2011-160234   3/1/2011  7/1/2011  ...          8.43         Medium  2011
16      IR-2011-770   3/1/2011  7/1/2011  ...          8.41         Medium  2011
17    ID-2011-80230   3/1/2011  9/1/2011  ...          8.34            Low  2011
18    ID-2011-80230   3/1/2011  9/1/2011  ...          8.17            Low  2011
19    ID-2011-12596   3/1/2011  8/1/2011  ...          7.74         Medium  2011
20    IN-2011-79397   3/1/2011  3/1/2011  ...          7.46       Critical  2011
21     IR-2011-7690   3/1/2011  8/1/2011  ...          5.91           High  2011
22      IR-2011-770   3/1/2011  7/1/2011  ...          5.16         Medium  2011
23     TZ-2011-7370   3/1/2011  8/1/2011  ...          5.11         Medium  2011
24     IZ-2011-4680   3/1/2011  7/1/2011  ...          3.57           High  2011

[25 rows x 21 columns]

In [12]:
#Standardise columns name
df.columns=(
    df.columns
    .str.replace(' ','_')
    .str.lower()
    .str.strip()
)

In [13]:
missing=df.isnull().mean()*100
print(missing)

order_id          0.0
order_date        0.0
ship_date         0.0
ship_mode         0.0
customer_name     0.0
segment           0.0
state             0.0
country           0.0
market            0.0
region            0.0
product_id        0.0
category          0.0
sub_category      0.0
product_name      0.0
sales             0.0
quantity          0.0
discount          0.0
profit            0.0
shipping_cost     0.0
order_priority    0.0
year              0.0
dtype: float64

In [14]:
n_dupes=df.duplicated().sum()
n_dupes

np.int64(0)